import type { Metadata } from "next";
import Link from "next/link";
import ThemeToggle from "@/app/components/ThemeToggle";
import "./globals.css";

export const metadata: Metadata = {
  title: "Web nha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            position: "sticky",
            top: 0,
            zIndex: 10,
            backdropFilter: "blur(8px)",
            background: "var(--header-bg)",
            borderBottom: "1px solid var(--header-border)",
          }}
        >
          <div
            style={{
              maxWidth: 980,
              margin: "0 auto",
              padding: "12px 20px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 16,
            }}
          >
            <div style={{ fontWeight: 700, letterSpacing: 0.3 }}>Web nha</div>
            <nav
              style={{
                display: "flex",
                alignItems: "center",
                gap: 16,
                fontSize: 14,
              }}
            >
              <Link href="/" style={{ color: "var(--text)" }}>
                Todo
              </Link>
              <Link href="/deal-filters" style={{ color: "var(--text)" }}>
                Deal
              </Link>
              <ThemeToggle />
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
